// Base de données des voitures électriques vendues en France (2025-2026).
// Données recueillies via recherche web (sources constructeurs + presse spé FR),
// collectées le 2026-06-03. Les champs `*Uncertain` / `chargeUnknown` signalent
// les valeurs NON confirmées officiellement — on préfère le dire plutôt que mentir.
// Prix = à partir de (catalogue France, €). Autonomie = WLTP max (km).

export type Chemistry = "LFP" | "NMC" | "LFP/NMC" | "inconnue";
export type VehicleStatus = "neuf" | "occasion";
export type Segment =
  | "Citadine"
  | "Compacte"
  | "Berline"
  | "SUV"
  | "SUV 7 places"
  | "Familiale / Van"
  | "Roadster";

export interface Vehicle {
  id: string;
  brand: string;
  model: string;
  version?: string;
  chemistry: Chemistry;
  capacityKwh: number | null; // capacité utile représentative
  rangeWltpKm: number; // autonomie WLTP max
  rangeNote?: string;
  trunkL: number | null;
  trunkNote?: string;
  priceFromEur: number | null; // prix de départ France
  priceNote?: string;
  charge1080: string; // libellé charge rapide
  fastChargeMin: number | null; // minutes ~10-80% pour filtrage (null si non publié)
  maxDcKw: number | null;
  connector: string;
  is800V: boolean;
  segment: Segment;
  status: VehicleStatus;
  officialUrl: string;
  sources: string;
  flags?: {
    priceUncertain?: boolean;
    trunkUncertain?: boolean;
    chemUncertain?: boolean;
    chargeUnknown?: boolean;
  };
}

export const vehicles: Vehicle[] = [
  // ─────────────── CITADINES ───────────────
  {
    id: "dacia-spring",
    brand: "Dacia",
    model: "Spring",
    version: "Essential / Extreme — 24,3 kWh",
    chemistry: "LFP",
    capacityKwh: 24.3,
    rangeWltpKm: 225,
    trunkL: 308,
    trunkNote: "1 004 L sièges rabattus",
    priceFromEur: 16900,
    priceNote: "hors aides · non éligible bonus",
    charge1080: "~30 min (20→80 %, DC 40 kW)",
    fastChargeMin: 30,
    maxDcKw: 40,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.dacia.fr/gamme-electrique-et-hybride/spring-citadine.html",
    sources: "Dacia · electrive · Motor1",
  },
  {
    id: "renault-twingo-etech",
    brand: "Renault",
    model: "Twingo E-Tech",
    version: "27,5 kWh — 82 ch",
    chemistry: "LFP",
    capacityKwh: 27.5,
    rangeWltpKm: 263,
    trunkL: 360,
    priceFromEur: 19500,
    priceNote: "< 20 000 € avec prime",
    charge1080: "~30 min (DC 50 kW, en option)",
    fastChargeMin: 30,
    maxDcKw: 50,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.renault.fr/vehicules-electriques/twingo-e-tech-electrique.html",
    sources: "L'Argus · média Renault",
    flags: { chargeUnknown: true },
  },
  {
    id: "byd-dolphin-surf",
    brand: "BYD",
    model: "Dolphin Surf",
    version: "30 / 43,2 kWh Blade",
    chemistry: "LFP",
    capacityKwh: 43.2,
    rangeWltpKm: 310,
    trunkL: 308,
    priceFromEur: 19990,
    priceNote: "≈ 13 990 € avec bonus",
    charge1080: "30 min (10→80 %, DC 65 kW)",
    fastChargeMin: 30,
    maxDcKw: 65,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.byd.com/fr/voitures-electriques/dolphin-surf",
    sources: "BYD · QuelleAutoChoisir",
  },
  {
    id: "citroen-e-c3",
    brand: "Citroën",
    model: "ë-C3",
    version: "Comfort Range — 44 kWh",
    chemistry: "LFP",
    capacityKwh: 44,
    rangeWltpKm: 326,
    trunkL: 310,
    priceFromEur: 23450,
    priceNote: "version Autonomie Urbaine < 20 000 €",
    charge1080: "26 min (20→80 %, DC 100 kW)",
    fastChargeMin: 26,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.citroen.fr/vehicules/e-c3.html",
    sources: "Citroën · L'Argus",
  },
  {
    id: "fiat-500e",
    brand: "Fiat",
    model: "500e",
    version: "42 kWh — 118 ch",
    chemistry: "NMC",
    capacityKwh: 42,
    rangeWltpKm: 320,
    trunkL: 185,
    priceFromEur: 28900,
    priceNote: "offres dès 13 900 € avec aides/LLD",
    charge1080: "~35 min (jusqu'à 80 %, DC 85 kW)",
    fastChargeMin: 35,
    maxDcKw: 85,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.fiat.fr/voitures-electriques/500e",
    sources: "automobile-propre · Fiat",
  },
  {
    id: "hyundai-inster",
    brand: "Hyundai",
    model: "Inster",
    version: "Long Range — 49 kWh",
    chemistry: "NMC",
    capacityKwh: 49,
    rangeWltpKm: 370,
    trunkL: 351,
    priceFromEur: 25350,
    charge1080: "~30 min (10→80 %, DC 85 kW)",
    fastChargeMin: 30,
    maxDcKw: 85,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.hyundai.com/fr/fr/modeles/inster-electric.html",
    sources: "Hyundai · meilleurelectrique",
  },
  {
    id: "renault-5-etech",
    brand: "Renault",
    model: "5 E-Tech",
    version: "Techno — 52 kWh",
    chemistry: "NMC",
    capacityKwh: 52,
    rangeWltpKm: 410,
    trunkL: 326,
    priceFromEur: 25000,
    priceNote: "gamme dès 20 680 € (bonus déduit)",
    charge1080: "< 30 min (15→80 %, DC 100 kW)",
    fastChargeMin: 30,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.renault.fr/vehicules-electriques/r5-e-tech-electrique.html",
    sources: "média Renault · L'Argus",
    flags: { chemUncertain: true, trunkUncertain: true },
  },

  // ─────────────── COMPACTES ───────────────
  {
    id: "mg4",
    brand: "MG",
    model: "MG4 (restylée)",
    version: "Premium — 64 kWh",
    chemistry: "LFP",
    capacityKwh: 64,
    rangeWltpKm: 452,
    rangeNote: "545 km en 77 kWh",
    trunkL: 350,
    priceFromEur: 33490,
    priceNote: "≈ 27 490 € avec remise",
    charge1080: "~25 min (10→80 %, DC)",
    fastChargeMin: 25,
    maxDcKw: 140,
    connector: "CCS Combo",
    is800V: false,
    segment: "Compacte",
    status: "neuf",
    officialUrl: "https://www.mgmotor.fr/model/mg4",
    sources: "L'Argus · City-Car",
  },
  {
    id: "vw-id3",
    brand: "Volkswagen",
    model: "ID.3",
    version: "Pro — 59 kWh",
    chemistry: "NMC",
    capacityKwh: 59,
    rangeWltpKm: 426,
    trunkL: 385,
    priceFromEur: 34990,
    charge1080: "~30 min (DC 120 kW)",
    fastChargeMin: 30,
    maxDcKw: 120,
    connector: "CCS Combo",
    is800V: false,
    segment: "Compacte",
    status: "neuf",
    officialUrl: "https://www.volkswagen.fr/fr/modeles-et-configurateur/id-3.html",
    sources: "Volkswagen · meilleurelectrique",
    flags: { chargeUnknown: true },
  },
  {
    id: "renault-megane-etech",
    brand: "Renault",
    model: "Mégane E-Tech",
    version: "60 kWh (LFP)",
    chemistry: "LFP",
    capacityKwh: 60,
    rangeWltpKm: 470,
    trunkL: 440,
    priceFromEur: 35900,
    priceNote: "prime CEE déduite",
    charge1080: "non publié (DC 130 kW)",
    fastChargeMin: null,
    maxDcKw: 130,
    connector: "CCS Combo",
    is800V: false,
    segment: "Compacte",
    status: "neuf",
    officialUrl: "https://www.renault.fr/vehicules-electriques/megane-e-tech-electrique.html",
    sources: "Faurie · go-electra",
    flags: { chargeUnknown: true },
  },
  {
    id: "cupra-born",
    brand: "Cupra",
    model: "Born (restylée)",
    version: "Plus — 58 kWh · 190 ch",
    chemistry: "NMC",
    capacityKwh: 58,
    rangeWltpKm: 484,
    trunkL: 385,
    priceFromEur: 40070,
    charge1080: "24 min (10→80 %, DC 165 kW)",
    fastChargeMin: 24,
    maxDcKw: 165,
    connector: "CCS Combo",
    is800V: false,
    segment: "Compacte",
    status: "neuf",
    officialUrl: "https://www.cupraofficial.fr/voitures/born",
    sources: "L'Argus · meilleurelectrique",
  },
  {
    id: "citroen-e-c4",
    brand: "Citroën",
    model: "ë-C4",
    version: "Autonomie étendue — 54 kWh",
    chemistry: "NMC",
    capacityKwh: 54,
    rangeWltpKm: 416,
    trunkL: 380,
    priceFromEur: 36800,
    priceNote: "≈ 32 800 € après bonus",
    charge1080: "~30 min (DC 100 kW)",
    fastChargeMin: 30,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "Compacte",
    status: "neuf",
    officialUrl: "https://www.citroen.fr/vehicules/nouvelle-e-c4.html",
    sources: "Stellantis Media · L'Argus",
    flags: { chargeUnknown: true },
  },
  {
    id: "peugeot-e-308",
    brand: "Peugeot",
    model: "e-308",
    version: "54 kWh — 156 ch",
    chemistry: "NMC",
    capacityKwh: 54,
    rangeWltpKm: 410,
    trunkL: 361,
    priceFromEur: 33050,
    charge1080: "26 min (20→80 %, DC 100 kW)",
    fastChargeMin: 26,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "Compacte",
    status: "neuf",
    officialUrl: "https://www.peugeot.fr/nos-vehicules/nouvelle-peugeot-308/electrique.html",
    sources: "Peugeot · euromotor · Beev",
  },
  {
    id: "peugeot-e-208",
    brand: "Peugeot",
    model: "e-208",
    version: "51 kWh — 156 ch",
    chemistry: "NMC",
    capacityKwh: 51,
    rangeWltpKm: 433,
    trunkL: 311,
    priceFromEur: 28400,
    priceNote: "136 ch dès 28 400 € · 156 ch dès 35 300 €",
    charge1080: "< 30 min (20→80 %, DC 100 kW)",
    fastChargeMin: 30,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.peugeot.fr/nos-vehicules/208/electrique.html",
    sources: "automobile-propre · les-lucioles",
    flags: { trunkUncertain: true },
  },

  // ─────────────── BERLINES ───────────────
  {
    id: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    version: "Propulsion (Standard) — ~64 kWh",
    chemistry: "LFP",
    capacityKwh: 64,
    rangeWltpKm: 534,
    trunkL: 594,
    trunkNote: "coffre + frunk",
    priceFromEur: 36990,
    priceNote: "≈ 33 090 € avec remise",
    charge1080: "non publié (DC 175 kW)",
    fastChargeMin: null,
    maxDcKw: 175,
    connector: "CCS Combo + Supercharger",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.tesla.com/fr_fr/model3",
    sources: "Tesla · L'Argus",
    flags: { chargeUnknown: true, trunkUncertain: true },
  },
  {
    id: "byd-seal",
    brand: "BYD",
    model: "Seal",
    version: "Design — 82,5 kWh Blade",
    chemistry: "LFP",
    capacityKwh: 82.5,
    rangeWltpKm: 570,
    trunkL: 485,
    trunkNote: "+ 53 L frunk",
    priceFromEur: 46990,
    charge1080: "~26 min (30→80 %, DC 150 kW)",
    fastChargeMin: 26,
    maxDcKw: 150,
    connector: "CCS Combo",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.byd.com/fr/voitures-electriques/seal",
    sources: "go-electra · leblogauto",
  },
  {
    id: "mazda-6e",
    brand: "Mazda",
    model: "6e",
    version: "78 kWh — berline",
    chemistry: "LFP",
    capacityKwh: 78,
    rangeWltpKm: 560,
    trunkL: 330,
    priceFromEur: 44000,
    priceNote: "annoncé sous 45 000 €",
    charge1080: "~15 min (30→80 %, DC)",
    fastChargeMin: null,
    maxDcKw: 165,
    connector: "CCS Combo",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.automobile-propre.com/voitures/mazda-6e/",
    sources: "automobile-propre · L'Argus",
    flags: { chargeUnknown: true },
  },
  {
    id: "kia-ev4",
    brand: "Kia",
    model: "EV4",
    version: "58,3 / 81,4 kWh",
    chemistry: "NMC",
    capacityKwh: 81.4,
    rangeWltpKm: 625,
    rangeNote: "jusqu'à 633 km en Fastback",
    trunkL: 435,
    trunkNote: "490 L en Fastback",
    priceFromEur: 38290,
    priceNote: "Long Range dès 42 890 €",
    charge1080: "29–31 min (10→80 %, DC 150 kW)",
    fastChargeMin: 31,
    maxDcKw: 150,
    connector: "CCS Combo",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.kia.com/fr/modeles/ev4/decouvrir/",
    sources: "Kia · Auto-Mag",
  },
  {
    id: "polestar-2",
    brand: "Polestar",
    model: "2",
    version: "69 / 82 kWh — fastback",
    chemistry: "NMC",
    capacityKwh: 82,
    rangeWltpKm: 659,
    trunkL: 407,
    trunkNote: "+ 41 L frunk",
    priceFromEur: 40900,
    priceNote: "Grande Autonomie 43 900 €",
    charge1080: "28 min (10→80 %, DC 205 kW)",
    fastChargeMin: 28,
    maxDcKw: 205,
    connector: "CCS Combo",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.polestar.com/fr/polestar-2/",
    sources: "automobile-propre · Beev",
  },
  {
    id: "hyundai-ioniq-6",
    brand: "Hyundai",
    model: "Ioniq 6",
    version: "63 / 77,4 kWh · 800 V",
    chemistry: "NMC",
    capacityKwh: 77.4,
    rangeWltpKm: 614,
    trunkL: 519,
    trunkNote: "+ 12 L frunk",
    priceFromEur: 44000,
    priceNote: "Long Range RWD 49 500 €",
    charge1080: "18 min (10→80 %, 800 V, DC 350 kW)",
    fastChargeMin: 18,
    maxDcKw: 350,
    connector: "CCS Combo",
    is800V: true,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.hyundai.com/fr/fr/modeles/ioniq6.html",
    sources: "Hyundai · euromotor",
  },
  {
    id: "vw-id7",
    brand: "Volkswagen",
    model: "ID.7",
    version: "77 / 86 kWh — berline & Tourer",
    chemistry: "NMC",
    capacityKwh: 86,
    rangeWltpKm: 702,
    trunkL: 532,
    trunkNote: "605 L en Tourer",
    priceFromEur: 53000,
    priceNote: "Tourer dès 53 700 €",
    charge1080: "< 30 min (10→80 %, DC 175–200 kW)",
    fastChargeMin: 28,
    maxDcKw: 200,
    connector: "CCS Combo",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.volkswagen.fr/fr/modeles-et-configurateur/id-7.html",
    sources: "Volkswagen · automobile-propre",
  },
  {
    id: "bmw-i4",
    brand: "BMW",
    model: "i4 eDrive40",
    version: "81,3 kWh — Gran Coupé",
    chemistry: "NMC",
    capacityKwh: 81.3,
    rangeWltpKm: 613,
    trunkL: 470,
    priceFromEur: 64000,
    charge1080: "~30 min (10→80 %, DC 205 kW)",
    fastChargeMin: 30,
    maxDcKw: 205,
    connector: "CCS Combo",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.bmw.fr/fr/tous-les-modeles/bmw-i/i4/bmw-i4-gran-coupe.html",
    sources: "Beev · L'Argus",
  },
  {
    id: "bmw-i5",
    brand: "BMW",
    model: "i5 eDrive40",
    version: "81,2 kWh — berline & Touring",
    chemistry: "NMC",
    capacityKwh: 81.2,
    rangeWltpKm: 627,
    trunkL: 490,
    trunkNote: "570 L en Touring",
    priceFromEur: 76250,
    priceNote: "non éligible bonus",
    charge1080: "~30 min (10→80 %, DC 205 kW)",
    fastChargeMin: 30,
    maxDcKw: 205,
    connector: "CCS Combo",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.bmw.fr/fr/tous-les-modeles/bmw-i/i5/bmw-i5-apercu.html",
    sources: "Beev · automobile-propre",
  },
  {
    id: "audi-a6-etron",
    brand: "Audi",
    model: "A6 e-tron",
    version: "Sportback / Avant — 100 kWh · 800 V",
    chemistry: "NMC",
    capacityKwh: 94.9,
    rangeWltpKm: 575,
    trunkL: 502,
    priceFromEur: null,
    priceNote: "prix France non trouvé — à vérifier sur audi.fr",
    charge1080: "< 30 min (800 V, DC 270 kW)",
    fastChargeMin: 21,
    maxDcKw: 270,
    connector: "CCS Combo",
    is800V: true,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.audi.fr/fr/gamme/a6-e-tron/a6-sportback-e-tron/",
    sources: "ev-market · L'Argus",
    flags: { priceUncertain: true },
  },
  {
    id: "audi-etron-gt",
    brand: "Audi",
    model: "e-tron GT",
    version: "quattro — ~97 kWh · 800 V",
    chemistry: "NMC",
    capacityKwh: 97,
    rangeWltpKm: 540,
    trunkL: 405,
    priceFromEur: null,
    priceNote: "prix France non trouvé — à vérifier sur audi.fr",
    charge1080: "< 30 min (800 V, DC 320 kW)",
    fastChargeMin: 18,
    maxDcKw: 320,
    connector: "CCS Combo",
    is800V: true,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.audi.fr/fr/gamme/e-tron-gt/",
    sources: "Beev · automobile-propre",
    flags: { priceUncertain: true },
  },
  {
    id: "ds-n8",
    brand: "DS",
    model: "N°8",
    version: "74 / 97,2 kWh",
    chemistry: "NMC",
    capacityKwh: 97.2,
    rangeWltpKm: 750,
    rangeNote: "572 km en 74 kWh",
    trunkL: 620,
    priceFromEur: 54970,
    charge1080: "27 min (jusqu'à 80 %, DC 160 kW)",
    fastChargeMin: 27,
    maxDcKw: 160,
    connector: "CCS Combo",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.dsautomobiles.fr/modeles-ds/dsn8.html",
    sources: "L'Argus · Stellantis Media",
  },
  {
    id: "bmw-i7",
    brand: "BMW",
    model: "i7 xDrive60",
    version: "112,5 kWh — berline de luxe",
    chemistry: "NMC",
    capacityKwh: 112.5,
    rangeWltpKm: 728,
    trunkL: 500,
    priceFromEur: 138300,
    charge1080: "28 min (10→80 %, DC 250 kW)",
    fastChargeMin: 28,
    maxDcKw: 250,
    connector: "CCS Combo",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.bmw.fr/fr/tous-les-modeles/serie-7/berline/bmw-i7-berline.html",
    sources: "BMW · Groupe GRIM",
  },

  // ─────────────── SUV ───────────────
  {
    id: "jeep-avenger",
    brand: "Jeep",
    model: "Avenger électrique",
    version: "54 kWh — 156 ch",
    chemistry: "NMC",
    capacityKwh: 54,
    rangeWltpKm: 400,
    trunkL: 355,
    priceFromEur: 35990,
    charge1080: "< 30 min (20→80 %, DC 100 kW)",
    fastChargeMin: 30,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.jeep.fr/nouvelle-jeep-avenger/electrique",
    sources: "L'Argus · automobile-propre",
  },
  {
    id: "byd-dolphin",
    brand: "BYD",
    model: "Dolphin",
    version: "Boost — 60,4 kWh Blade",
    chemistry: "LFP",
    capacityKwh: 60.4,
    rangeWltpKm: 427,
    trunkL: 345,
    priceFromEur: 33990,
    charge1080: "30 min (10→80 %, DC 85 kW)",
    fastChargeMin: 30,
    maxDcKw: 85,
    connector: "CCS Combo",
    is800V: false,
    segment: "Compacte",
    status: "neuf",
    officialUrl: "https://www.byd.com/fr/offres-du-moment/dolphin",
    sources: "go-electra · ev-market",
  },
  {
    id: "renault-4-etech",
    brand: "Renault",
    model: "4 E-Tech",
    version: "52 kWh — Techno",
    chemistry: "NMC",
    capacityKwh: 52,
    rangeWltpKm: 409,
    trunkL: 420,
    trunkNote: "1 405 L sièges rabattus",
    priceFromEur: 33490,
    priceNote: "40 kWh dès 29 990 €",
    charge1080: "~30 min (20→80 %, DC 100 kW)",
    fastChargeMin: 30,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.renault.fr/vehicules-electriques/r4-e-tech-electrique.html",
    sources: "ISIOHM · go-electra",
    flags: { trunkUncertain: true },
  },
  {
    id: "citroen-e-c3-aircross",
    brand: "Citroën",
    model: "ë-C3 Aircross",
    version: "44 / 54 kWh — SUV familial",
    chemistry: "LFP/NMC",
    capacityKwh: 54,
    rangeWltpKm: 400,
    trunkL: 460,
    trunkNote: "jusqu'à 7 places",
    priceFromEur: 19990,
    priceNote: "haut de gamme 33 990 €",
    charge1080: "26 min (20→80 %, DC 100 kW)",
    fastChargeMin: 26,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.citroen.fr/vehicules/ec3-aircross.html",
    sources: "L'Argus · euromotor",
  },
  {
    id: "mazda-mx-30",
    brand: "Mazda",
    model: "MX-30",
    version: "35,5 kWh — 145 ch (100 % élec.)",
    chemistry: "NMC",
    capacityKwh: 35.5,
    rangeWltpKm: 200,
    trunkL: 366,
    priceFromEur: 38250,
    priceNote: "⚠ existe aussi en R-EV (hybride, hors liste)",
    charge1080: "~26 min (20→80 %, DC 50 kW)",
    fastChargeMin: 26,
    maxDcKw: 50,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.mazda.fr/showroom/mazda-mx-30/",
    sources: "automobile-propre · les-lucioles",
  },
  {
    id: "mg-zs-ev",
    brand: "MG",
    model: "ZS EV",
    version: "51 / 72 kWh",
    chemistry: "LFP/NMC",
    capacityKwh: 72,
    rangeWltpKm: 440,
    trunkL: 448,
    priceFromEur: 31990,
    priceNote: "≈ 28 000 € avec bonus",
    charge1080: "~40 min (5→80 %, DC 92 kW)",
    fastChargeMin: null,
    maxDcKw: 92,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.automobile-propre.com/voitures/mg-zs-ev/",
    sources: "automobile-propre · Beev",
    flags: { chargeUnknown: true },
  },
  {
    id: "mg-s5-ev",
    brand: "MG",
    model: "S5 EV",
    version: "49 / 64 kWh — SUV compact",
    chemistry: "LFP/NMC",
    capacityKwh: 64,
    rangeWltpKm: 480,
    trunkL: 453,
    priceFromEur: 32490,
    priceNote: "≈ 28 990 € avec bonus",
    charge1080: "24–28 min (10→80 %, DC 120–139 kW)",
    fastChargeMin: 28,
    maxDcKw: 139,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.mgmotor.fr/model/mgs5",
    sources: "automobile-propre",
  },
  {
    id: "skoda-elroq",
    brand: "Škoda",
    model: "Elroq",
    version: "50 / 85 — 52 à 82 kWh",
    chemistry: "NMC",
    capacityKwh: 82,
    rangeWltpKm: 560,
    trunkL: 470,
    priceFromEur: 33300,
    priceNote: "85x Loft AWD 47 900 €",
    charge1080: "~25 min (10→80 %, DC 175 kW)",
    fastChargeMin: 25,
    maxDcKw: 175,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.skoda.fr/gamme/elroq/elroq",
    sources: "Škoda · automobile-propre",
  },
  {
    id: "volvo-ex30",
    brand: "Volvo",
    model: "EX30",
    version: "Extended Range — 69 kWh",
    chemistry: "NMC",
    capacityKwh: 69,
    rangeWltpKm: 480,
    rangeNote: "344 km en 51 kWh Core (LFP)",
    trunkL: 318,
    priceFromEur: 36490,
    priceNote: "Extended Range 41 990 €",
    charge1080: "~26 min (10→80 %, DC)",
    fastChargeMin: 26,
    maxDcKw: 153,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.volvocars.com/fr/cars/ex30-electric/",
    sources: "L'Argus · automobile-propre",
    flags: { trunkUncertain: true },
  },
  {
    id: "volvo-ex40",
    brand: "Volvo",
    model: "EX40",
    version: "ex-XC40 Recharge — 69 / 82 kWh",
    chemistry: "NMC",
    capacityKwh: 82,
    rangeWltpKm: 575,
    trunkL: 460,
    priceFromEur: 48990,
    charge1080: "~26 min (10→80 %, DC)",
    fastChargeMin: 26,
    maxDcKw: 200,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.volvocars.com/fr/cars/ex40-electric/",
    sources: "actu-automobile · Volvo",
  },
  {
    id: "volvo-ec40",
    brand: "Volvo",
    model: "EC40",
    version: "ex-C40 Recharge — 69 / 82 kWh",
    chemistry: "NMC",
    capacityKwh: 82,
    rangeWltpKm: 585,
    trunkL: 404,
    priceFromEur: 52900,
    priceNote: "Twin Ultimate jusqu'à 67 400 €",
    charge1080: "~26 min (10→80 %, DC)",
    fastChargeMin: 26,
    maxDcKw: 200,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.volvocars.com/fr/cars/ec40-electric/",
    sources: "sports-cars · Volvo",
    flags: { trunkUncertain: true },
  },
  {
    id: "peugeot-e-2008",
    brand: "Peugeot",
    model: "e-2008",
    version: "54 kWh — 136 / 156 ch",
    chemistry: "NMC",
    capacityKwh: 54,
    rangeWltpKm: 406,
    trunkL: 434,
    priceFromEur: 36000,
    charge1080: "~30 min (20→80 %, DC 100 kW)",
    fastChargeMin: 30,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.peugeot.fr/nos-vehicules/suv-peugeot-2008/electrique.html",
    sources: "euromotor · Smartactive",
    flags: { trunkUncertain: true },
  },
  {
    id: "peugeot-e-3008",
    brand: "Peugeot",
    model: "e-3008",
    version: "73 kWh — 210 ch",
    chemistry: "NMC",
    capacityKwh: 73,
    rangeWltpKm: 527,
    trunkL: 520,
    trunkNote: "sources divergent : 520–588 L",
    priceFromEur: 40990,
    priceNote: "Allure 44 990 € · GT 46 990 €",
    charge1080: "~21–27 min (20→80 %, DC 160 kW)",
    fastChargeMin: 27,
    maxDcKw: 160,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.peugeot.fr/nos-vehicules/peugeot-3008/electrique.html",
    sources: "Beev · les-lucioles",
    flags: { trunkUncertain: true },
  },
  {
    id: "kia-ev3",
    brand: "Kia",
    model: "EV3",
    version: "Long Range — 81,4 kWh",
    chemistry: "NMC",
    capacityKwh: 81.4,
    rangeWltpKm: 605,
    trunkL: 460,
    priceFromEur: 40990,
    priceNote: "Earth 43 090 €",
    charge1080: "~31 min (10→80 %, 400 V)",
    fastChargeMin: 31,
    maxDcKw: 128,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.kia.com/fr/modeles/ev3/decouvrir/",
    sources: "automobile-propre · L'Argus",
  },
  {
    id: "kia-niro-ev",
    brand: "Kia",
    model: "Niro EV",
    version: "64,8 kWh — 204 ch",
    chemistry: "NMC",
    capacityKwh: 64.8,
    rangeWltpKm: 460,
    trunkL: 475,
    priceFromEur: 44640,
    charge1080: "~43 min (DC 77 kW)",
    fastChargeMin: null,
    maxDcKw: 77,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.kia.com/fr/modeles/niro/decouvrir/",
    sources: "Beev · L'Argus",
    flags: { chargeUnknown: true },
  },
  {
    id: "hyundai-kona-electric",
    brand: "Hyundai",
    model: "Kona Electric",
    version: "65,4 kWh — 217 ch",
    chemistry: "NMC",
    capacityKwh: 65.4,
    rangeWltpKm: 514,
    trunkL: 466,
    priceFromEur: 36900,
    charge1080: "~41 min (10→80 %, DC 100 kW)",
    fastChargeMin: 41,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.hyundai.com/fr/fr/modeles/kona-electric.html",
    sources: "Hyundai · Smartactive",
  },
  {
    id: "hyundai-ioniq-5",
    brand: "Hyundai",
    model: "Ioniq 5",
    version: "77,4 kWh — 229 ch · 800 V",
    chemistry: "NMC",
    capacityKwh: 77.4,
    rangeWltpKm: 570,
    rangeNote: "507 km en propulsion standard",
    trunkL: 520,
    priceFromEur: 52000,
    charge1080: "18 min (10→80 %, 800 V, DC 350 kW)",
    fastChargeMin: 18,
    maxDcKw: 350,
    connector: "CCS Combo",
    is800V: true,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.hyundai.com/fr/fr/modeles/ioniq5/performance.html",
    sources: "Caradisiac · hyundai.news",
  },
  {
    id: "kia-ev6",
    brand: "Kia",
    model: "EV6 (restylée)",
    version: "84 kWh · 800 V",
    chemistry: "NMC",
    capacityKwh: 84,
    rangeWltpKm: 582,
    trunkL: 490,
    priceFromEur: 43950,
    priceNote: "Air 84 kWh 47 450 €",
    charge1080: "18 min (10→80 %, 800 V, DC 240 kW)",
    fastChargeMin: 18,
    maxDcKw: 240,
    connector: "CCS Combo",
    is800V: true,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.kia.com/fr/modeles/ev6/decouvrir/",
    sources: "AVEM · L'Argus",
  },
  {
    id: "byd-atto-3-evo",
    brand: "BYD",
    model: "Atto 3 EVO",
    version: "74,8 kWh Blade · 800 V",
    chemistry: "LFP",
    capacityKwh: 74.8,
    rangeWltpKm: 510,
    trunkL: 490,
    trunkNote: "+ 101 L frunk",
    priceFromEur: 38990,
    priceNote: "Excellence AWD 42 490 €",
    charge1080: "25 min (10→80 %, 800 V, DC 220 kW)",
    fastChargeMin: 25,
    maxDcKw: 220,
    connector: "CCS Combo",
    is800V: true,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.byd.com/fr/voitures-electriques/atto-3-evo",
    sources: "L'Argus · mondial.paris",
  },
  {
    id: "byd-sealion-7",
    brand: "BYD",
    model: "Sealion 7",
    version: "82,5 / 91,3 kWh Blade · 800 V",
    chemistry: "LFP",
    capacityKwh: 82.5,
    rangeWltpKm: 502,
    trunkL: 500,
    priceFromEur: 46990,
    priceNote: "Excellence 56 490 €",
    charge1080: "24 min (10→80 %, 800 V, DC 230 kW)",
    fastChargeMin: 24,
    maxDcKw: 230,
    connector: "CCS Combo",
    is800V: true,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.byd.com/fr/voitures-electriques/sealion-7",
    sources: "BYmyCAR · QuelleAutoChoisir",
    flags: { trunkUncertain: true },
  },
  {
    id: "skoda-enyaq",
    brand: "Škoda",
    model: "Enyaq 85",
    version: "77 kWh utiles — 286 ch",
    chemistry: "NMC",
    capacityKwh: 77,
    rangeWltpKm: 581,
    trunkL: 585,
    priceFromEur: 46270,
    priceNote: "éligible bonus",
    charge1080: "< 30 min (DC 135 kW)",
    fastChargeMin: 28,
    maxDcKw: 135,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.skoda.fr/gamme/enyaq/enyaq",
    sources: "L'Argus · Beev",
    flags: { chargeUnknown: true },
  },
  {
    id: "vw-id4",
    brand: "Volkswagen",
    model: "ID.4",
    version: "52 / 77 kWh — SUV",
    chemistry: "NMC",
    capacityKwh: 77,
    rangeWltpKm: 530,
    trunkL: 543,
    priceFromEur: 38990,
    priceNote: "Pro 43 990 € · GTX 53 990 €",
    charge1080: "~28 min (10→80 %, DC 175 kW)",
    fastChargeMin: 28,
    maxDcKw: 175,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.volkswagen.fr/fr/modeles-et-configurateur/id-4.html",
    sources: "euromotor · Beev",
  },
  {
    id: "vw-id5",
    brand: "Volkswagen",
    model: "ID.5",
    version: "77 kWh — SUV coupé",
    chemistry: "NMC",
    capacityKwh: 77,
    rangeWltpKm: 550,
    trunkL: 549,
    priceFromEur: 49000,
    priceNote: "prix à vérifier",
    charge1080: "~28 min (10→80 %, DC 175 kW)",
    fastChargeMin: 28,
    maxDcKw: 175,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.volkswagen.fr/fr/modeles-et-configurateur/id-5.html",
    sources: "automobile-propre",
    flags: { priceUncertain: true, trunkUncertain: true },
  },
  {
    id: "nissan-ariya",
    brand: "Nissan",
    model: "Ariya",
    version: "63 / 87 kWh — SUV",
    chemistry: "NMC",
    capacityKwh: 87,
    rangeWltpKm: 536,
    trunkL: 468,
    priceFromEur: 44200,
    charge1080: "~35–40 min (DC 130 kW)",
    fastChargeMin: null,
    maxDcKw: 130,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.nissan.fr/vehicules/neufs/ariya.html",
    sources: "Nissan · ezoomed",
    flags: { chargeUnknown: true },
  },
  {
    id: "toyota-bz4x",
    brand: "Toyota",
    model: "bZ4X (2026)",
    version: "57,7 / 74,7 kWh",
    chemistry: "NMC",
    capacityKwh: 74.7,
    rangeWltpKm: 591,
    trunkL: 669,
    trunkNote: "version Touring",
    priceFromEur: 48400,
    priceNote: "Touring · Performance AWD dès 51 900 €",
    charge1080: "28 min (10→80 %, DC 150 kW)",
    fastChargeMin: 28,
    maxDcKw: 150,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.toyota.fr/vehicules-neufs/bz4x",
    sources: "L'Argus · actu-automobile",
  },
  {
    id: "cupra-tavascan",
    brand: "Cupra",
    model: "Tavascan",
    version: "77 kWh — SUV coupé",
    chemistry: "NMC",
    capacityKwh: 77,
    rangeWltpKm: 568,
    rangeNote: "~435 km sur la nouvelle entrée 58 kWh",
    trunkL: 540,
    priceFromEur: 46990,
    priceNote: "VZ Extreme jusqu'à 71 330 €",
    charge1080: "~28 min (10→80 %, DC 135 kW)",
    fastChargeMin: 28,
    maxDcKw: 135,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.cupraofficial.fr/voitures/tavascan",
    sources: "Cupra · motor1 · ev-market",
  },
  {
    id: "audi-q4-etron",
    brand: "Audi",
    model: "Q4 e-tron (restylé)",
    version: "45 / Performance — 59 à 79 kWh",
    chemistry: "NMC",
    capacityKwh: 79,
    rangeWltpKm: 582,
    trunkL: 520,
    trunkNote: "527 L en Sportback",
    priceFromEur: 45990,
    charge1080: "28 min (10→80 %, DC 185 kW)",
    fastChargeMin: 28,
    maxDcKw: 185,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.audi.fr/fr/gamme/q4-e-tron/",
    sources: "automobile-propre · L'Argus",
  },
  {
    id: "bmw-ix1",
    brand: "BMW",
    model: "iX1 eDrive20",
    version: "64,8 kWh utiles",
    chemistry: "NMC",
    capacityKwh: 64.8,
    rangeWltpKm: 516,
    rangeNote: "468 km en xDrive30",
    trunkL: 490,
    priceFromEur: 46990,
    priceNote: "M Sport 51 040 €",
    charge1080: "29 min (10→80 %, DC 130 kW)",
    fastChargeMin: 29,
    maxDcKw: 130,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.bmw.fr/fr/tous-les-modeles/bmw-i/ix1/bmw-ix1.html",
    sources: "L'Argus · automobile-propre",
  },
  {
    id: "bmw-ix2",
    brand: "BMW",
    model: "iX2 eDrive20",
    version: "64,8 kWh utiles — SUV coupé",
    chemistry: "NMC",
    capacityKwh: 64.8,
    rangeWltpKm: 516,
    rangeNote: "479 km en xDrive30",
    trunkL: 525,
    priceFromEur: 46990,
    charge1080: "29 min (20→80 %, DC 130 kW)",
    fastChargeMin: 29,
    maxDcKw: 130,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.bmw.fr/fr/tous-les-modeles/bmw-i/ix2/bmw-ix2-apercu.html",
    sources: "L'Argus · automobile-propre",
  },
  {
    id: "bmw-ix3",
    brand: "BMW",
    model: "iX3 (Neue Klasse)",
    version: "xDrive40 / 50 — 800 V",
    chemistry: "NMC",
    capacityKwh: 82.6,
    rangeWltpKm: 805,
    rangeNote: "635 km en xDrive40",
    trunkL: 520,
    trunkNote: "jusqu'à 1 750 L",
    priceFromEur: 55900,
    priceNote: "xDrive50 64 500 €",
    charge1080: "~21 min (800 V, DC 300–400 kW)",
    fastChargeMin: 21,
    maxDcKw: 400,
    connector: "CCS Combo",
    is800V: true,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.bmw.fr/fr/tous-les-modeles/x-series/ix3/bmw-ix3.html",
    sources: "L'Argus · automobile-propre",
    flags: { trunkUncertain: true },
  },
  {
    id: "bmw-ix",
    brand: "BMW",
    model: "iX xDrive45",
    version: "~100 kWh — grand SUV",
    chemistry: "NMC",
    capacityKwh: 94.8,
    rangeWltpKm: 602,
    trunkL: 500,
    priceFromEur: 90000,
    priceNote: "prix indicatif — à vérifier",
    charge1080: "~35 min (DC ~195 kW)",
    fastChargeMin: 35,
    maxDcKw: 195,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.bmw.fr/fr/tous-les-modeles/bmw-i/ix/bmw-ix.html",
    sources: "BMW · larevueautomobile",
    flags: { priceUncertain: true, chargeUnknown: true },
  },
  {
    id: "audi-q6-etron",
    brand: "Audi",
    model: "Q6 e-tron",
    version: "Performance — 100 kWh · 800 V",
    chemistry: "NMC",
    capacityKwh: 94.9,
    rangeWltpKm: 671,
    trunkL: 526,
    priceFromEur: 70900,
    priceNote: "S line 74 500 €",
    charge1080: "~21 min (10→80 %, 800 V, DC 270 kW)",
    fastChargeMin: 21,
    maxDcKw: 270,
    connector: "CCS Combo",
    is800V: true,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.audi.fr/fr/gamme/q6-e-tron/",
    sources: "L'Argus · automobile-propre",
  },
  {
    id: "audi-q8-etron",
    brand: "Audi",
    model: "Q8 e-tron",
    version: "50 / 55 — 89 à 106 kWh utiles",
    chemistry: "NMC",
    capacityKwh: 106,
    rangeWltpKm: 600,
    trunkL: 569,
    trunkNote: "+ 62 L frunk",
    priceFromEur: 89300,
    charge1080: "~31 min (DC 170 kW)",
    fastChargeMin: 31,
    maxDcKw: 170,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.audi.fr/fr/gamme/q8-e-tron/",
    sources: "Beev · automobile-propre",
  },
  {
    id: "porsche-macan-electric",
    brand: "Porsche",
    model: "Macan Electric",
    version: "100 kWh · 800 V",
    chemistry: "NMC",
    capacityKwh: 95,
    rangeWltpKm: 641,
    trunkL: 540,
    trunkNote: "+ 84 L frunk",
    priceFromEur: 82959,
    priceNote: "Turbo 118 910 €",
    charge1080: "21 min (10→80 %, 800 V, DC 270 kW)",
    fastChargeMin: 21,
    maxDcKw: 270,
    connector: "CCS Combo",
    is800V: true,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.porsche.com/france/models/macan/macan-electric-models/",
    sources: "ev-market · motor1",
  },
  {
    id: "mercedes-eqa",
    brand: "Mercedes",
    model: "EQA",
    version: "66,5 / 70,5 kWh — SUV compact",
    chemistry: "NMC",
    capacityKwh: 70.5,
    rangeWltpKm: 560,
    trunkL: 340,
    priceFromEur: 51100,
    priceNote: "4MATIC dès 59 750 €",
    charge1080: "~30 min (DC 100 kW)",
    fastChargeMin: 30,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.mercedes-benz.fr/passengercars/models/suv/eqa/overview.html",
    sources: "euromotor · automobile-propre",
  },
  {
    id: "mercedes-eqe-suv",
    brand: "Mercedes",
    model: "EQE SUV",
    version: "~90 kWh — SUV premium",
    chemistry: "NMC",
    capacityKwh: 90,
    rangeWltpKm: 590,
    trunkL: 520,
    priceFromEur: 93150,
    charge1080: "~30 min (10→80 %, DC 170 kW)",
    fastChargeMin: 30,
    maxDcKw: 170,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.mercedes-benz.fr/passengercars/models/suv/eqe/overview.html",
    sources: "L'Argus · automobile-propre",
  },
  {
    id: "polestar-3",
    brand: "Polestar",
    model: "3",
    version: "106 kWh — grand SUV",
    chemistry: "NMC",
    capacityKwh: 106,
    rangeWltpKm: 647,
    trunkL: 484,
    trunkNote: "+ 32 L frunk",
    priceFromEur: 78950,
    charge1080: "30 min (10→80 %, DC 250 kW)",
    fastChargeMin: 30,
    maxDcKw: 250,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.polestar.com/fr/polestar-3/",
    sources: "automobile-propre · Rouleur Électrique",
  },
  {
    id: "polestar-4",
    brand: "Polestar",
    model: "4",
    version: "100 kWh — SUV coupé",
    chemistry: "NMC",
    capacityKwh: 94,
    rangeWltpKm: 620,
    trunkL: 526,
    priceFromEur: 49900,
    priceNote: "remise jusqu'au 30/06/2026 · catalogue 61 800 €",
    charge1080: "30 min (10→80 %, DC 200 kW)",
    fastChargeMin: 30,
    maxDcKw: 200,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.polestar.com/fr/polestar-4/",
    sources: "L'Argus · Voiture autonome",
    flags: { trunkUncertain: true },
  },

  // ─────────────── SUV 7 PLACES ───────────────
  {
    id: "peugeot-e-5008",
    brand: "Peugeot",
    model: "e-5008",
    version: "73 / 98 kWh — 7 places",
    chemistry: "NMC",
    capacityKwh: 98,
    rangeWltpKm: 668,
    rangeNote: "502 km en 73 kWh",
    trunkL: 748,
    trunkNote: "259 L en 7 places",
    priceFromEur: 46690,
    priceNote: "98 kWh dès 51 490 € · AWD 59 990 €",
    charge1080: "~30 min (à 80 %, DC 160 kW)",
    fastChargeMin: 30,
    maxDcKw: 160,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV 7 places",
    status: "neuf",
    officialUrl: "https://www.peugeot.fr/our-range/new-peugeot-e-5008.html",
    sources: "euromotor · autosblog",
  },
  {
    id: "kia-ev9",
    brand: "Kia",
    model: "EV9",
    version: "99,8 kWh — 7 places · 800 V",
    chemistry: "NMC",
    capacityKwh: 99.8,
    rangeWltpKm: 563,
    trunkL: 333,
    trunkNote: "jusqu'à 2 320 L",
    priceFromEur: 64400,
    priceNote: "Air 65 990 € · GT-Line 82 990 €",
    charge1080: "24 min (10→80 %, 800 V, DC 210 kW)",
    fastChargeMin: 24,
    maxDcKw: 210,
    connector: "CCS Combo",
    is800V: true,
    segment: "SUV 7 places",
    status: "neuf",
    officialUrl: "https://www.kia.com/fr/modeles/ev9/decouvrir/",
    sources: "AVEM · autosblog",
    flags: { trunkUncertain: true },
  },
  {
    id: "hyundai-ioniq-9",
    brand: "Hyundai",
    model: "Ioniq 9",
    version: "110,3 kWh — 7 places · 800 V",
    chemistry: "NMC",
    capacityKwh: 110.3,
    rangeWltpKm: 620,
    trunkL: 620,
    trunkNote: "jusqu'à 2 000 L+",
    priceFromEur: 69900,
    charge1080: "24 min (10→80 %, 800 V, DC 350 kW)",
    fastChargeMin: 24,
    maxDcKw: 350,
    connector: "CCS Combo",
    is800V: true,
    segment: "SUV 7 places",
    status: "neuf",
    officialUrl: "https://www.hyundai.com/fr/fr/modeles/ioniq9.html",
    sources: "L'Argus · go-electra",
    flags: { trunkUncertain: true },
  },
  {
    id: "volvo-ex90",
    brand: "Volvo",
    model: "EX90",
    version: "88 à 107 kWh — 7 places",
    chemistry: "NMC",
    capacityKwh: 107,
    rangeWltpKm: 617,
    trunkL: 669,
    trunkNote: "jusqu'à 1 915 L · + frunk",
    priceFromEur: 84950,
    priceNote: "Ultra 89 950 €",
    charge1080: "~22 min (10→80 %, DC 250 kW)",
    fastChargeMin: 22,
    maxDcKw: 250,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV 7 places",
    status: "neuf",
    officialUrl: "https://www.volvocars.com/fr/cars/ex90-electric/specifications/",
    sources: "automobile-propre · vivacar",
    flags: { chargeUnknown: true },
  },
  {
    id: "mercedes-eqb",
    brand: "Mercedes",
    model: "EQB",
    version: "66,5 / 70,5 kWh — 7 places",
    chemistry: "NMC",
    capacityKwh: 70.5,
    rangeWltpKm: 415,
    trunkL: 495,
    trunkNote: "+ 30 L frunk",
    priceFromEur: 59200,
    priceNote: "350 4MATIC dès 68 150 €",
    charge1080: "~32 min (à 80 %, DC 100 kW)",
    fastChargeMin: 32,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV 7 places",
    status: "neuf",
    officialUrl: "https://www.mercedes-benz.fr/passengercars/models/suv/eqb/overview.html",
    sources: "automobile-propre · Beev",
  },

  // ─────────────── FAMILIALE / VAN ───────────────
  {
    id: "vw-id-buzz",
    brand: "Volkswagen",
    model: "ID. Buzz",
    version: "79 / 86 kWh — combi / 7 places",
    chemistry: "NMC",
    capacityKwh: 86,
    rangeWltpKm: 469,
    trunkL: 1340,
    priceFromEur: 52850,
    charge1080: "< 30 min (10→80 %, DC 185–200 kW)",
    fastChargeMin: 28,
    maxDcKw: 200,
    connector: "CCS Combo",
    is800V: false,
    segment: "Familiale / Van",
    status: "neuf",
    officialUrl: "https://www.volkswagen-utilitaires.fr/fr/modeles/id-buzz.html",
    sources: "automobile-propre · L'Argus",
  },

  // ─────────────── ROADSTER ───────────────
  {
    id: "mg-cyberster",
    brand: "MG",
    model: "Cyberster",
    version: "77 kWh — roadster",
    chemistry: "NMC",
    capacityKwh: 77,
    rangeWltpKm: 570,
    rangeNote: "443 km en AWD",
    trunkL: 249,
    priceFromEur: 54990,
    priceNote: "Trophy AWD 64 990 €",
    charge1080: "38 min (10→80 %, DC 150 kW)",
    fastChargeMin: 38,
    maxDcKw: 150,
    connector: "CCS Combo",
    is800V: false,
    segment: "Roadster",
    status: "neuf",
    officialUrl: "https://www.mgmotor.fr/model/cyberster",
    sources: "automobile-propre · Beev",
  },

  // ─────────────── TESLA MODEL Y (toutes versions) ───────────────
  {
    id: "tesla-model-y-standard-propulsion",
    brand: "Tesla",
    model: "Model Y Standard",
    version: "Propulsion (RWD) — 63,9 kWh",
    chemistry: "LFP",
    capacityKwh: 63.9,
    rangeWltpKm: 534,
    trunkL: 854,
    trunkNote: "+ 117 L frunk · 2 118 L rabattu",
    priceFromEur: 40990,
    charge1080: "27 min (10→80 %, DC 250 kW)",
    fastChargeMin: 27,
    maxDcKw: 250,
    connector: "CCS Combo + Supercharger",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.tesla.com/fr_fr/modely",
    sources: "automobile-propre · euromotor",
  },
  {
    id: "tesla-model-y-standard-ga",
    brand: "Tesla",
    model: "Model Y Standard",
    version: "Grande Autonomie (RWD)",
    chemistry: "NMC",
    capacityKwh: null,
    rangeWltpKm: 657,
    rangeNote: "la plus sobre de la gamme",
    trunkL: 854,
    trunkNote: "+ 117 L frunk",
    priceFromEur: 44990,
    charge1080: "~27 min (DC 250 kW)",
    fastChargeMin: 27,
    maxDcKw: 250,
    connector: "CCS Combo + Supercharger",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.tesla.com/fr_fr/modely",
    sources: "Motor1 · blogTesla",
    flags: { chemUncertain: true },
  },
  {
    id: "tesla-model-y-premium-ga-rwd",
    brand: "Tesla",
    model: "Model Y Premium",
    version: "Grande Autonomie Propulsion (RWD) — ~79 kWh",
    chemistry: "NMC",
    capacityKwh: 79,
    rangeWltpKm: 600,
    trunkL: 854,
    trunkNote: "+ 117 L frunk",
    priceFromEur: 46990,
    charge1080: "~27 min (DC 250 kW)",
    fastChargeMin: 27,
    maxDcKw: 250,
    connector: "CCS Combo + Supercharger",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.tesla.com/fr_fr/modely",
    sources: "L'Argus · euromotor",
    flags: { chemUncertain: true },
  },
  {
    id: "tesla-model-y-premium-ga-awd",
    brand: "Tesla",
    model: "Model Y Premium",
    version: "Grande Autonomie Intégrale (AWD) — 462 ch",
    chemistry: "NMC",
    capacityKwh: 79,
    rangeWltpKm: 568,
    trunkL: 854,
    trunkNote: "+ 117 L frunk",
    priceFromEur: 52990,
    charge1080: "~27 min (DC 250 kW)",
    fastChargeMin: 27,
    maxDcKw: 250,
    connector: "CCS Combo + Supercharger",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.tesla.com/fr_fr/modely",
    sources: "L'Argus · cardesign",
    flags: { chemUncertain: true, trunkUncertain: true },
  },
  {
    id: "tesla-model-y-performance",
    brand: "Tesla",
    model: "Model Y Performance",
    version: "AWD — 507 ch · 0–100 en 3,7 s",
    chemistry: "NMC",
    capacityKwh: 79,
    rangeWltpKm: 514,
    trunkL: 854,
    trunkNote: "+ 117 L frunk",
    priceFromEur: 59990,
    charge1080: "~27 min (DC 250 kW)",
    fastChargeMin: 27,
    maxDcKw: 250,
    connector: "CCS Combo + Supercharger",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.tesla.com/fr_fr/modely",
    sources: "Car Design · L'Argus",
    flags: { chemUncertain: true },
  },

  {
    id: "leapmotor-t03",
    brand: "Leapmotor",
    model: "T03",
    version: "37,3 kWh — citadine",
    chemistry: "LFP",
    capacityKwh: 37.3,
    rangeWltpKm: 265,
    trunkL: 210,
    priceFromEur: 16900,
    priceNote: "prime CEE incluse",
    charge1080: "~36 min (à 80 %, DC 48 kW)",
    fastChargeMin: 36,
    maxDcKw: 48,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.leapmotor.net/t03",
    sources: "automobile-propre · Stellantis",
  },
  {
    id: "fiat-grande-panda",
    brand: "Fiat",
    model: "Grande Panda",
    version: "44 kWh — citadine",
    chemistry: "LFP",
    capacityKwh: 44,
    rangeWltpKm: 320,
    trunkL: 412,
    priceFromEur: 22400,
    priceNote: "offres dès 13 900 € avec aides",
    charge1080: "27 min (20→80 %, DC 100 kW)",
    fastChargeMin: 27,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.fiat.fr/modeles/grande-panda-electrique",
    sources: "Fiat · Stellantis Media",
    flags: { chemUncertain: true },
  },
  {
    id: "alpine-a290",
    brand: "Alpine",
    model: "A290",
    version: "52 kWh — citadine sportive",
    chemistry: "NMC",
    capacityKwh: 52,
    rangeWltpKm: 380,
    trunkL: 326,
    priceFromEur: 38700,
    charge1080: "30 min (10→80 %, DC 100 kW)",
    fastChargeMin: 30,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.alpinecars.fr/offres-particuliers/offres-financement-a290.html",
    sources: "média Alpine · automobile-propre",
  },
  {
    id: "mini-cooper-se-j01",
    brand: "Mini",
    model: "Cooper SE",
    version: "54,2 kWh (nouvelle génération)",
    chemistry: "NMC",
    capacityKwh: 54.2,
    rangeWltpKm: 402,
    trunkL: 210,
    priceFromEur: 39900,
    priceNote: "≈ 35 900 € après bonus",
    charge1080: "~25 min (10→80 %, DC 95 kW)",
    fastChargeMin: 25,
    maxDcKw: 95,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.mini.fr/fr_FR/home/range/all-electric-mini-cooper.html",
    sources: "euromotor · La Centrale",
  },
  {
    id: "mini-aceman",
    brand: "Mini",
    model: "Aceman",
    version: "42,5 / 54,2 kWh — crossover",
    chemistry: "NMC",
    capacityKwh: 54.2,
    rangeWltpKm: 406,
    rangeNote: "310 km en version E (42,5 kWh)",
    trunkL: 300,
    priceFromEur: 37500,
    priceNote: "SE dès ~41 000 €",
    charge1080: "~30 min (10→80 %, DC 95 kW)",
    fastChargeMin: 30,
    maxDcKw: 95,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.mini.fr/fr_FR/home/range/all-electric-mini-aceman.html",
    sources: "automobile-propre · ezoomed",
  },
  {
    id: "smart-1",
    brand: "Smart",
    model: "#1",
    version: "49 / 66 kWh — SUV compact",
    chemistry: "NMC",
    capacityKwh: 66,
    rangeWltpKm: 440,
    rangeNote: "310 km en 49 kWh",
    trunkL: 313,
    priceFromEur: 39990,
    charge1080: "~30 min (10→80 %, DC 150 kW)",
    fastChargeMin: 30,
    maxDcKw: 150,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://fr.smart.com/fr/models/hashtag-one/",
    sources: "automobile-propre · Beev",
    flags: { trunkUncertain: true },
  },
  {
    id: "opel-corsa-electric",
    brand: "Opel",
    model: "Corsa Electric",
    version: "51 kWh — 156 ch",
    chemistry: "NMC",
    capacityKwh: 51,
    rangeWltpKm: 402,
    trunkL: 267,
    priceFromEur: 34990,
    priceNote: "< 30 000 € après bonus",
    charge1080: "26 min (20→80 %, DC 100 kW)",
    fastChargeMin: 26,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.opel.fr/vehicules/gamme-corsa/new-corsa/points-forts.html",
    sources: "automobile-propre · les-lucioles",
    flags: { priceUncertain: true },
  },
  {
    id: "opel-mokka-electric",
    brand: "Opel",
    model: "Mokka Electric",
    version: "54 kWh — 156 ch",
    chemistry: "NMC",
    capacityKwh: 54,
    rangeWltpKm: 403,
    trunkL: 350,
    priceFromEur: 36900,
    charge1080: "27 min (20→80 %, DC 100 kW)",
    fastChargeMin: 27,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.opel.fr/vehicules/nouveau-mokka/mokka/overview-new.html",
    sources: "automobile-propre · ev-market",
    flags: { priceUncertain: true },
  },
  {
    id: "honda-eny1",
    brand: "Honda",
    model: "e:Ny1",
    version: "62 kWh — SUV",
    chemistry: "NMC",
    capacityKwh: 62,
    rangeWltpKm: 412,
    trunkL: 361,
    priceFromEur: 47990,
    priceNote: "remises importantes (jusqu'à -12 800 €)",
    charge1080: "~45 min (10→80 %, DC 78 kW)",
    fastChargeMin: 45,
    maxDcKw: 78,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://auto.honda.fr/cars/new/e-ny1-electric-suv/overview.html",
    sources: "Honda · automobile-propre",
    flags: { trunkUncertain: true },
  },
  {
    id: "leapmotor-c10",
    brand: "Leapmotor",
    model: "C10",
    version: "67 kWh — SUV familial",
    chemistry: "LFP",
    capacityKwh: 67,
    rangeWltpKm: 420,
    trunkL: 435,
    priceFromEur: 36400,
    priceNote: "non éligible bonus (fab. Chine)",
    charge1080: "~30 min (30→80 %, DC 90 kW)",
    fastChargeMin: 30,
    maxDcKw: 90,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.leapmotor.net/fr/c10",
    sources: "automobile-propre · mondial.paris",
  },

  {
    id: "abarth-500e",
    brand: "Abarth",
    model: "500e",
    version: "42 kWh — citadine sportive",
    chemistry: "NMC",
    capacityKwh: 42,
    rangeWltpKm: 265,
    trunkL: 185,
    priceFromEur: 36900,
    charge1080: "~30 min (à 80 %, DC 85 kW)",
    fastChargeMin: 30,
    maxDcKw: 85,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "neuf",
    officialUrl: "https://www.abarth.fr/mobilite-electrique",
    sources: "automobile-propre · L'Argus",
  },
  {
    id: "peugeot-e-408",
    brand: "Peugeot",
    model: "e-408",
    version: "58,2 kWh — Fastback",
    chemistry: "NMC",
    capacityKwh: 58.2,
    rangeWltpKm: 456,
    trunkL: 468,
    priceFromEur: 42700,
    charge1080: "31 min (20→80 %, DC 120 kW)",
    fastChargeMin: 31,
    maxDcKw: 120,
    connector: "CCS Combo",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.peugeot.fr/nos-vehicules/nouvelle-peugeot-408/electrique.html",
    sources: "Peugeot · L'Argus",
  },
  {
    id: "byd-seal-u",
    brand: "BYD",
    model: "Seal U EV",
    version: "71,8 / 87 kWh Blade — SUV",
    chemistry: "LFP",
    capacityKwh: 87,
    rangeWltpKm: 500,
    rangeNote: "420 km en version Comfort",
    trunkL: 552,
    priceFromEur: 41990,
    charge1080: "~30 min (à 80 %, DC 150 kW)",
    fastChargeMin: 30,
    maxDcKw: 150,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.byd.com/fr/voitures-electriques/seal-u",
    sources: "BYD · ev-market",
  },
  {
    id: "subaru-solterra",
    brand: "Subaru",
    model: "Solterra (2026)",
    version: "73,1 kWh — AWD",
    chemistry: "NMC",
    capacityKwh: 73.1,
    rangeWltpKm: 509,
    trunkL: 452,
    priceFromEur: 48990,
    priceNote: "version + à 52 990 €",
    charge1080: "28 min (10→80 %, DC 150 kW)",
    fastChargeMin: 28,
    maxDcKw: 150,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.subaru.fr/solterra.aspx",
    sources: "L'Argus · automobile-propre",
    flags: { trunkUncertain: true },
  },
  {
    id: "xpeng-g6",
    brand: "XPeng",
    model: "G6",
    version: "80,8 / 87,5 kWh · 800 V",
    chemistry: "NMC",
    capacityKwh: 87.5,
    rangeWltpKm: 570,
    rangeNote: "525 km en 80,8 kWh",
    trunkL: 571,
    priceFromEur: 46990,
    priceNote: "non éligible bonus (fab. Chine)",
    charge1080: "12 min (10→80 %, 800 V, DC 451 kW)",
    fastChargeMin: 12,
    maxDcKw: 451,
    connector: "CCS Combo",
    is800V: true,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.xpeng.com/model/g6",
    sources: "go-electra · QuelleAutoChoisir",
    flags: { chemUncertain: true, trunkUncertain: true },
  },
  {
    id: "xpeng-g9",
    brand: "XPeng",
    model: "G9",
    version: "79 / 93,1 kWh · 800 V",
    chemistry: "LFP",
    capacityKwh: 92.2,
    rangeWltpKm: 585,
    rangeNote: "460 km en 79 kWh",
    trunkL: 660,
    trunkNote: "+ 88 L frunk",
    priceFromEur: 59990,
    priceNote: "AWD Performance 69 990 €",
    charge1080: "12 min (10→80 %, 800 V, DC 525 kW)",
    fastChargeMin: 12,
    maxDcKw: 525,
    connector: "CCS Combo",
    is800V: true,
    segment: "SUV",
    status: "neuf",
    officialUrl: "https://www.xpeng.com/model/g9",
    sources: "Voiture autonome · automobile-propre",
  },
  {
    id: "mercedes-eqe",
    brand: "Mercedes",
    model: "EQE",
    version: "90,6 kWh — berline",
    chemistry: "NMC",
    capacityKwh: 90.6,
    rangeWltpKm: 654,
    trunkL: 430,
    priceFromEur: null,
    priceNote: "prix neuf 2026 non confirmé — à vérifier",
    charge1080: "~32 min (10→80 %, DC 170 kW)",
    fastChargeMin: 32,
    maxDcKw: 170,
    connector: "CCS Combo",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.mercedes-benz.fr/passengercars/models/saloon/eqe/overview.html",
    sources: "ezoomed · BPM Cars",
    flags: { priceUncertain: true },
  },
  {
    id: "mercedes-eqs",
    brand: "Mercedes",
    model: "EQS",
    version: "112 kWh — berline de luxe",
    chemistry: "NMC",
    capacityKwh: 112,
    rangeWltpKm: 799,
    rangeNote: "jusqu'à ~925 km annoncé 2026 (à confirmer)",
    trunkL: 610,
    priceFromEur: 107350,
    charge1080: "~31 min (10→80 %, DC 200 kW)",
    fastChargeMin: 31,
    maxDcKw: 200,
    connector: "CCS Combo",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.mercedes-benz.fr/passengercars/models/saloon/eqs/overview.html",
    sources: "L'Argus · mondial.paris",
    flags: { trunkUncertain: true, chargeUnknown: true },
  },

  {
    id: "tesla-model-s",
    brand: "Tesla",
    model: "Model S",
    version: "Dual Motor — 100 kWh",
    chemistry: "NMC",
    capacityKwh: 100,
    rangeWltpKm: 634,
    rangeNote: "Plaid : ~600 km, 1 020 ch",
    trunkL: 793,
    trunkNote: "+ frunk · 1 645 L rabattu",
    priceFromEur: 109990,
    priceNote: "Plaid 119 990 €",
    charge1080: "non publié (DC 250 kW, Supercharger)",
    fastChargeMin: null,
    maxDcKw: 250,
    connector: "CCS Combo + Supercharger",
    is800V: false,
    segment: "Berline",
    status: "neuf",
    officialUrl: "https://www.tesla.com/fr_fr/models",
    sources: "Tesla · tout-sur-lauto",
    flags: { chargeUnknown: true },
  },
  {
    id: "tesla-model-x",
    brand: "Tesla",
    model: "Model X",
    version: "Dual Motor — 100 kWh · 7 places",
    chemistry: "NMC",
    capacityKwh: 100,
    rangeWltpKm: 649,
    rangeNote: "Plaid : 609 km, 1 020 ch",
    trunkL: 1050,
    trunkNote: "+ frunk · portes Falcon Wing",
    priceFromEur: 114990,
    priceNote: "Plaid 124 990 €",
    charge1080: "non publié (DC 250 kW, Supercharger)",
    fastChargeMin: null,
    maxDcKw: 250,
    connector: "CCS Combo + Supercharger",
    is800V: false,
    segment: "SUV 7 places",
    status: "neuf",
    officialUrl: "https://www.tesla.com/fr_fr/modelx",
    sources: "Tesla · voitureautonome",
    flags: { chargeUnknown: true, trunkUncertain: true },
  },

  // ─────────────── OCCASION (plus commercialisés neufs / fin de série) ───────────────
  {
    id: "renault-zoe",
    brand: "Renault",
    model: "Zoe",
    version: "ZE50 R135 — 52 kWh",
    chemistry: "NMC",
    capacityKwh: 52,
    rangeWltpKm: 395,
    trunkL: 338,
    priceFromEur: 10000,
    priceNote: "prix occasion indicatif",
    charge1080: "~56 min (DC 50 kW, en option)",
    fastChargeMin: 56,
    maxDcKw: 50,
    connector: "CCS Combo (option) / Type 2",
    is800V: false,
    segment: "Citadine",
    status: "occasion",
    officialUrl: "https://www.automobile-propre.com/voitures/renault-zoe/",
    sources: "automobile-propre · les-lucioles",
    flags: { priceUncertain: true, trunkUncertain: true },
  },
  {
    id: "nissan-leaf-e-plus",
    brand: "Nissan",
    model: "Leaf e+",
    version: "62 kWh — CHAdeMO",
    chemistry: "NMC",
    capacityKwh: 62,
    rangeWltpKm: 385,
    rangeNote: "270 km en 40 kWh",
    trunkL: 435,
    priceFromEur: 15000,
    priceNote: "prix occasion indicatif",
    charge1080: "~60 min (DC 100 kW, CHAdeMO)",
    fastChargeMin: 60,
    maxDcKw: 100,
    connector: "CHAdeMO (≠ CCS)",
    is800V: false,
    segment: "Compacte",
    status: "occasion",
    officialUrl: "https://www.automobile-propre.com/voitures/nissan-leaf-2/",
    sources: "automobile-propre · Nissan",
    flags: { priceUncertain: true },
  },
  {
    id: "bmw-i3",
    brand: "BMW",
    model: "i3",
    version: "120 Ah — 42 kWh",
    chemistry: "NMC",
    capacityKwh: 37.9,
    rangeWltpKm: 305,
    trunkL: 260,
    priceFromEur: 17000,
    priceNote: "prix occasion indicatif",
    charge1080: "~42 min (à 80 %, DC 50 kW)",
    fastChargeMin: 42,
    maxDcKw: 50,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "occasion",
    officialUrl: "https://www.automobile-propre.com/voitures/bmw-i3/",
    sources: "automobile-propre · fiches-auto",
    flags: { priceUncertain: true },
  },
  {
    id: "ds-3-crossback-etense",
    brand: "DS",
    model: "3 Crossback E-Tense",
    version: "50 kWh — 136 ch",
    chemistry: "NMC",
    capacityKwh: 46,
    rangeWltpKm: 341,
    trunkL: 350,
    priceFromEur: 18000,
    priceNote: "prix occasion indicatif",
    charge1080: "~30 min (20→80 %, DC 100 kW)",
    fastChargeMin: 30,
    maxDcKw: 100,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "occasion",
    officialUrl: "https://www.automobile-propre.com/voitures/ds3-crossback-electrique/",
    sources: "L'Argus · automobile-propre",
    flags: { priceUncertain: true },
  },
  {
    id: "mini-cooper-se",
    brand: "Mini",
    model: "Cooper SE",
    version: "32,6 kWh (ancienne génération)",
    chemistry: "NMC",
    capacityKwh: 32.6,
    rangeWltpKm: 234,
    trunkL: 211,
    priceFromEur: 16000,
    priceNote: "prix occasion indicatif",
    charge1080: "~35 min (à 80 %, DC 50 kW)",
    fastChargeMin: 35,
    maxDcKw: 50,
    connector: "CCS Combo",
    is800V: false,
    segment: "Citadine",
    status: "occasion",
    officialUrl: "https://www.automobile-propre.com/voitures/mini-cooper-se/",
    sources: "automobile-propre · EV Database",
    flags: { priceUncertain: true },
  },
  {
    id: "kia-e-niro",
    brand: "Kia",
    model: "e-Niro",
    version: "64 kWh — 204 ch (ancienne génération)",
    chemistry: "NMC",
    capacityKwh: 64,
    rangeWltpKm: 455,
    trunkL: 451,
    priceFromEur: 16000,
    priceNote: "prix occasion indicatif",
    charge1080: "~45 min (DC 77 kW)",
    fastChargeMin: 45,
    maxDcKw: 77,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "occasion",
    officialUrl: "https://www.automobile-propre.com/voitures/kia-e-niro-electrique/",
    sources: "L'Argus · meilleurelectrique",
    flags: { priceUncertain: true },
  },
  {
    id: "mercedes-eqc",
    brand: "Mercedes",
    model: "EQC",
    version: "80 kWh — 408 ch",
    chemistry: "NMC",
    capacityKwh: 80,
    rangeWltpKm: 414,
    trunkL: 500,
    priceFromEur: 36000,
    priceNote: "prix occasion indicatif",
    charge1080: "~40 min (10→80 %, DC 110 kW)",
    fastChargeMin: 40,
    maxDcKw: 110,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "occasion",
    officialUrl: "https://www.automobile-propre.com/voitures/mercedes-eqc/",
    sources: "automobile-propre · L'Argus",
    flags: { priceUncertain: true },
  },
  {
    id: "audi-etron-55",
    brand: "Audi",
    model: "e-tron 55 quattro",
    version: "95 kWh (1ʳᵉ génération)",
    chemistry: "NMC",
    capacityKwh: 86,
    rangeWltpKm: 437,
    trunkL: 660,
    priceFromEur: 35000,
    priceNote: "prix occasion indicatif",
    charge1080: "~30 min (DC 150 kW)",
    fastChargeMin: 30,
    maxDcKw: 150,
    connector: "CCS Combo",
    is800V: false,
    segment: "SUV",
    status: "occasion",
    officialUrl: "https://fr.motor1.com/reviews/350805/audi-e-tron-test-consommation/",
    sources: "EV Database · fiches-auto",
    flags: { priceUncertain: true },
  },
];

// ───────────────────────── Helpers ─────────────────────────

export interface VehicleFilters {
  q?: string;
  brands?: string[];
  chemistries?: Chemistry[];
  segments?: Segment[];
  status?: VehicleStatus[];
  priceMin?: number;
  priceMax?: number;
  rangeMin?: number;
  trunkMin?: number;
  only800V?: boolean;
}

export function filterVehicles(list: Vehicle[], f: VehicleFilters): Vehicle[] {
  return list.filter((v) => {
    if (f.q) {
      const hay = `${v.brand} ${v.model} ${v.version ?? ""}`.toLowerCase();
      if (!hay.includes(f.q.toLowerCase())) return false;
    }
    if (f.brands?.length && !f.brands.includes(v.brand)) return false;
    if (f.chemistries?.length && !f.chemistries.includes(v.chemistry)) return false;
    if (f.segments?.length && !f.segments.includes(v.segment)) return false;
    if (f.status?.length && !f.status.includes(v.status)) return false;
    if (f.only800V && !v.is800V) return false;
    if (typeof f.priceMin === "number" && (v.priceFromEur ?? Infinity) < f.priceMin) return false;
    if (typeof f.priceMax === "number" && (v.priceFromEur ?? -Infinity) > f.priceMax) return false;
    if (typeof f.rangeMin === "number" && v.rangeWltpKm < f.rangeMin) return false;
    if (typeof f.trunkMin === "number" && (v.trunkL ?? 0) < f.trunkMin) return false;
    return true;
  });
}

export const brands = Array.from(new Set(vehicles.map((v) => v.brand))).sort();
export const segments: Segment[] = [
  "Citadine",
  "Compacte",
  "Berline",
  "SUV",
  "SUV 7 places",
  "Familiale / Van",
  "Roadster",
];
export const chemistries: Chemistry[] = ["LFP", "NMC", "LFP/NMC", "inconnue"];

export function getVehicle(id: string): Vehicle | undefined {
  return vehicles.find((v) => v.id === id);
}
